// src/pages/HomePage.jsx
import React from 'react'; // Import React if using JSX transform older than automatic
import useTypewriter from '../hooks/useTypewriter'; // Import the custom hook

function HomePage() {
  const pageKey = 'visits_home'; // Unique key for this page

  // Define the full text for the paragraphs we want to animate
  const welcomeText = "Welcome. This node provides access to curated data streams, project archives, and operational schematics.";
  const navigateText = "Navigate via the directory links or engage the Command Line Interface (CLI) for advanced queries.";
  const objectiveText = "Our objective: Building Better Worlds... one byte at a time.";

  // Pass the pageKey to the hook
  const typedWelcomeText = useTypewriter(welcomeText, 50, `${pageKey}_welcome`); // Add unique suffix if needed per element, or use one key per page
  const typedNavigateText = useTypewriter(navigateText, 40, `${pageKey}_navigate`);
  const typedObjectiveText = useTypewriter(objectiveText, 60, `${pageKey}_objective`);

  // Check if *any* of the effects are still animating for the cursor
  const isTyping = typedWelcomeText !== welcomeText || typedNavigateText !== navigateText || typedObjectiveText !== objectiveText;

  return (
    // Using tui-window for consistent section styling
    <div className="tui-window" style={{ marginTop: '20px', minHeight: '400px' }}>
      <h2 className="tui-title">C:\HOME&gt; SYSTEM ONLINE</h2>
      <div className="tui-panel">
        <p>WEYLAND CORP TERMINAL INTERFACE v3.9.96</p> {/* Static text */}
        <p>ACCESS GRANTED. USER: GUEST</p> {/* Static text */}
        <p>----------------------------------------------------------------------</p>
        <p>Initializing data streams...</p>
        <div className="tui-progress" data-value="25" data-label="CORE SYS: 25%"></div>
        <p style={{marginTop: '10px'}}>Establishing secure connection...</p>
        <div className="tui-progress" data-value="50" data-label="NETWORK: 50%"></div>
        <p style={{marginTop: '10px'}}>Loading archival data...</p>
        <div className="tui-progress" data-value="75" data-label="ARCHIVES: 75%"></div>
        <p style={{marginTop: '10px'}}>SYSTEM READY. AWAITING DIRECTIVE.</p>
        <p>----------------------------------------------------------------------</p>
        {/* Render the text generated by the hook */}
        <p>
          {typedWelcomeText}
          {/* Show cursor only if this specific text is animating */}
          {typedWelcomeText !== welcomeText ? '_' : ''}
        </p>
        <p>
          {typedNavigateText}
          {typedNavigateText !== navigateText ? '_' : ''}
        </p>
        <p>
          <em>{typedObjectiveText}</em>
          {typedObjectiveText !== objectiveText ? '_' : ''}
        </p>
        <br />
        {/* Show prompt only after typing is done? Or keep it static? Let's keep static for now */}
        <p>C:\HOME&gt; _</p>
      </div>
    </div>
  );
}

export default HomePage;